<a href="https://colab.research.google.com/github/KuchkorovBoburbek/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:

print(pd.__version__)

2.2.2

In [ ]:
# Dictionary
mydataset = {
  'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Bugatti', 'BMW'],
  'counts': [3, 7, 2, 5, 8, 4, 18]
}
print(mydataset, "\n")

df = pd.DataFrame(mydataset)
print(df, "\n")

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Bugatti', 'BMW'], 'counts': [3, 7, 2, 5, 8, 4, 18]}

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5  Bugatti       4
6      BMW      18

In [ ]:

# head method  boshidan nechtadir
df.head(4) # default 5 rows

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       5

In [ ]:

# tail method oxiridan nechtadir
df.tail(2) # default 5 rows

      cars  counts
5  Bugatti       4
6      BMW      18

In [ ]:
# State Property: shape, column, dtypes
a = df.shape
print("=====\n", a)

b = df.columns
print("=====\n", b)

c = df.dtypes # har bir column ning type
print("=====\n", c)

df["cars"] = df["cars"].astype("string")
d = df.dtypes
print("=====\n", d)

=====
 (7, 2)
=====
 Index(['cars', 'counts'], dtype='object')
=====
 cars      object
counts     int64
dtype: object
=====
 cars      string[python]
counts             int64
dtype: object

In [ ]:
# describe method - numeric statistikani hosil qilib beradi
df.describe()
# df.describe(include="all")

          counts
count   7.000000
mean    6.714286
std     5.407226
min     2.000000
25%     3.500000
50%     5.000000
75%     7.500000
max    18.000000

In [ ]:

# iloc (integer location) method - kerakli malumotlarini tanlab olish

print("=====\n", df.iloc[0])

print("=====\n", df.iloc[1])

print("=====\n", df.iloc[1,0]) # [row location, column location]

print("\n")
df.iloc[1:4]

=====
 cars      BMW
counts      3
Name: 0, dtype: object
=====
 cars      Volvo
counts        7
Name: 1, dtype: object
=====
 Volvo

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       5

In [ ]:
# loc method - kerakli malumotlarni ma'lum bir columndan tanlab olish
df.loc[1:4, "cars"]

1      Volvo
2       Ford
3      Tesla
4    Ferrari
Name: cars, dtype: string

In [ ]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5  Bugatti       4
6      BMW      18

In [ ]:
df["counts"] >= 3

0     True
1     True
2    False
3     True
4     True
5     True
6     True
Name: counts, dtype: bool

In [ ]:
df[df["counts"] >= 3]
# df[df["cars"] == "BMW"]

      cars  counts
0      BMW       3
1    Volvo       7
3    Tesla       5
4  Ferrari       8
5  Bugatti       4
6      BMW      18

In [ ]:
# mean
a = df.mean(numeric_only=True)
b = df["counts"].mean()

print(a, "\n")
print(b, "\n")

print("======\n")
print(df.min())

print("======\n")
print(df.max())

print("======\n")
print(df.median(numeric_only=True))

print("======\n")
print(df.count()) # None value bolmaganlarni chiqarib berad

counts    6.714286
dtype: float64

6.714285714285714

======

cars      BMW
counts      2
dtype: object
======

cars      Volvo
counts       18
dtype: object
======

counts    5.0
dtype: float64
======

cars      7
counts    7
dtype: int64

/tmp/ipykernel_4680/628027810.py:9: FutureWarning: <class 'pandas.core.arrays.string_.StringArray'>._reduce will require a `keepdims` parameter in the future
  print(df.min())
/tmp/ipykernel_4680/628027810.py:12: FutureWarning: <class 'pandas.core.arrays.string_.StringArray'>._reduce will require a `keepdims` parameter in the future
  print(df.max())

In [ ]:

dataset = {
  'cars': ["BMW", "Volvo", "Ford", None, "Ferrari", "Bugatti", None],
  'counts': [3, 7, 2, None, 8, 14, 17]
}

df_missing = pd.DataFrame(dataset)
print(df_missing, "\n")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3     None     NaN
4  Ferrari     8.0
5  Bugatti    14.0
6     None    17.0

In [ ]:
# None holatdagi malumotlarni aniqlaymiz
df_missing.isnull().sum()

cars      2
counts    1
dtype: int64

In [ ]:
df_clean = df_missing.dropna()
print(df_clean)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [ ]:
# df_missing.dropna(how="all") # har ikkalasi None bolganini ochiradi
df_missing.dropna(axis=0) # tanlangan 0-row 1-column None boyicha ochiradi
# df_missing.dropna(subset="counts") # tanlangan column None tozalaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [ ]:

# fillna method - ma'lumotlarni tog'irlab toldirib oladi

# df_missing.fillna("unknown")
df_missing.fillna({"cars": "unknown", "counts": 0})

In [32]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# pd.read_excel("Titanic-Dataset.xlsx")
# pd.read_json("Titanic-Dataset.json")

In [34]:
df.to_excel("output.xlsx")
newdf = pd.read_excel("output.xlsx")
newdf.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.to_excel("test.xlsx", index=False)
newdf = pd.read_excel("output.xlsx")
newdf.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
pd.Series(["BMW", "Tesla", "Bugatti"])

0        BMW
1      Tesla
2    Bugatti
dtype: object